Create initial i18n framework
fedimint/ui pull request #24
Opened 2023-06-04 18:48 UTC by benalleng

Creates a new languages package for import in both the gateway and guardian ui.

Initially opened in [mfedimint/fedimint](https://github.com/fedimint/fedimint/pull/2541)

I tried my best to make sure i caught every stray piece of copy but there's a lot to go through!

TODO:

 -  Create Better translation README to explain how all copy should be created moving forward.

2023-06-06 01:41 UTC, EthnTuttle requested changes
I'm not sure of a way to test this? I saw that you added an `es.json` but changing my preferred browser language did not update anything for me. Does the framework use a manual toggle?
Awesome work! Looking forward to testing with Spanish.

2023-06-06 01:41 UTC, EthnTuttle commented on apps/guardian-ui/src/components/ConnectGuardians.tsx
> +                <Tag colorScheme='orange'>{t('connect_guardians.pedning')}</Tag>
nit: typo pending

2023-06-06 01:41 UTC, EthnTuttle commented on apps/guardian-ui/src/components/RunDKG.tsx
> +            setError(`${t('run_dkg.error_default')} ${status}`);
We should keep '' around `${status}`

2023-06-06 01:41 UTC, EthnTuttle commented on apps/guardian-ui/src/languages/en.json
> +    "error": "Something went wrong."
This could probably in `common`. We use it several times. Hopefully our error handling improves from this point. 😅

2023-06-06 01:41 UTC, EthnTuttle commented on packages/utils/README.md
> +`fedimint-ui/apps/gateway-ui/src/translation/en/gateway.json`
This path needs updated.

2023-06-06 01:41 UTC, EthnTuttle commented on packages/utils/README.md
~~Seems like there are few places in the README that need updated from the port over from the other repo.~~
nvm, I see your comment in the PR description.

2023-06-06 01:44 UTC, EthnTuttle commented
@benalleng are you in the Discord? if not, check out chat.fedimint.org

2023-06-06 11:35 UTC, benalleng commented
> I'm not sure of a way to test this? I saw that you added an `es.json` but changing my preferred browser language did not update anything for me. 

So for some reason `LanguageDetector` saves your prefered language into local storage on the app so you'll need to clear your local storage as well when switching the browser to Spanish.

As for a language selector I think that would be a good secondary add, I'm just not sure where to put a component like that with the current gateway/guardian UI setup. I was in the design call last week to listen in and get some more insight about that as well

2023-06-06 11:40 UTC, EthnTuttle commented
We can def wire up a selector after some design feedback. Good idea.

I’ll test after clearing my local cache. Thnx much for the clarification.

Sent from Proton Mail for iOS

On Tue, Jun 6, 2023 at 07:35, Ben Allen ***@***.***(mailto:On Tue, Jun 6, 2023 at 07:35, Ben Allen <<a href=)> wrote:

>> I'm not sure of a way to test this? I saw that you added an es.json but changing my preferred browser language did not update anything for me.
>
> So for some reason LanguageDetector saves your prefered language into local storage on the app so you'll need to clear your local storage as well when switching the browser to Spanish.
>
> As for a language selector I think that would be a good secondary add, I'm just not sure where to put a component like that with the current gateway/guardian UI setup. I was in the design call last week to listen in and get some more insight about that as well
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/fedimint/ui/pull/24#issuecomment-1578558255), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/A7YP53OPMZHLMXUFOI44TMDXJ4IZRANCNFSM6AAAAAAY2DPHNE).
> You are receiving this because you commented.Message ID: ***@***.***>

2023-07-20 00:59 UTC, EthnTuttle approved these changes
I think this is a great start to lay the basic framework. Unless I'm misunderstanding, this still allows us to hard code text for quick iteration, but lays the framework needed.

2023-07-20 01:15 UTC, okjodom commented on packages/utils/src/i18n.tsx
> +export const i18nProvider = (namespace: Array<any>) => {
🥇

2023-07-20 01:21 UTC, okjodom approved these changes

2023-07-20 01:22 UTC, merged