Feature/admin main
fedimint/ui pull request #46
Opened 2023-07-01 19:29 UTC by IgboPharaoh

This pr introduces the AdminMain section of the FederationAdmin page. 

The AdminMain section currently contains the following sections:
- **Community custody section** 
>- Federation Balance tabs
>-  Chart section

- **Epochs**
- > Epoch component

**NOTE**:  The chart section hasn't been added yet as currently there are ongoing discussions on how best to implement the chart and display accompanying metrics. Also, a chart package to be used hasn't been decided upon.

Possible chart package option to look at: [Rechart](https://recharts.org/en-US/api)

[figma link](https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?node-id=854%3A21343&mode=dev)

pictorial representation of components built
<img width="1208" alt="Screenshot 2023-07-01 at 20 20 05" src="https://github.com/fedimint/ui/assets/87058633/dd9de0ca-9a60-4f68-b97b-eb98a7a4578c">

2023-07-02 10:40 UTC, EthnTuttle commented on apps/guardian-ui/src/assets/svgs/ecash.svg
Can this have a transparent "e" like the banknotes and bitcoin svg's? This won't be useful when switching themes.

2023-07-07 16:42 UTC, wbobeirne commented on apps/guardian-ui/src/assets/svgs/ecash.svg
All icons should use `currentColor` instead of hard-coded values as well, so that they can adapt to their container's `color` css property.

2023-07-07 17:39 UTC, IgboPharaoh commented on apps/guardian-ui/src/assets/svgs/ecash.svg
Thanks!!! will make the necessary corrections and update the PR

2023-07-12 00:15 UTC, EthnTuttle requested changes

2023-07-13 04:31 UTC, IgboPharaoh commented on apps/guardian-ui/src/components/AdminMain.tsx
> +import { ReactComponent as BankNotesIcon } from '../assets/svgs/bitcoin-white.svg';
Changes have been implemented

2023-07-14 01:32 UTC, merged