feat: homepage actions and federation selector
fedimint/ui pull request #527
Opened 2024-09-18 20:28 UTC by Kodylow

Took another pass at improving the home page, it's much better now with a nice selector

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/f652a9f8-f168-4adb-9103-11157cc91eeb">

2024-09-19 23:47 UTC, tvolk131 requested changes
Just one small thing, otherwise LGTM and works on my machine!

2024-09-19 23:47 UTC, tvolk131 commented on apps/router/src/index.tsx
> +// ... existing imports ...
AI leftovers? 👀

2024-09-20 01:20 UTC, Kodylow commented on apps/router/src/index.tsx
> +// ... existing imports ...
oh lol haha yup fixing

2024-09-20 14:05 UTC, tvolk131 approved these changes
Send it! 🚀

2024-09-20 14:05 UTC, merged